export { default as Container } from './Container/Container';
export { default as SideBar } from './SideBar/SideBar';
export { default as Header } from './Header/Header';
export { default as Realtors } from './Realtors/Realtors';
export { default as Features } from './Features/Features';
export { default as Story } from './Story/Story';
export { default as Homes } from './Homes/Homes';
export { default as Gallery } from './Gallery/Gallery';
export { default as Footer } from './Footer/Footer';
